export const CHAIN_CONTRACT_VERSION = 'v1';

export const SUPPORTED_SOLANA_CLUSTERS = ['mainnet-beta', 'devnet', 'testnet'] as const;
export type SupportedSolanaCluster = (typeof SUPPORTED_SOLANA_CLUSTERS)[number];

export const PHOTO_PROOF_PROGRAM_ID_BASE58 = '3i6eNpCFvXhMg8LESAutXWKUtAey9mAbTziLLuUc78Hu';
export const BUBBLEGUM_PROGRAM_ID_BASE58 = 'DTNhearU7zbKfR4XSzWUGY4TFUgb6s86GY6T1aWPALEP';

export const RECORD_PHOTO_PROOF_DISCRIMINATOR_SEED = 'global:record_photo_proof';
export const RECORD_PHOTO_PROOF_DISCRIMINATOR_BYTES = 8;
export const RECORD_PHOTO_PROOF_HASH_BYTES = 32;
export const RECORD_PHOTO_PROOF_NUMERIC_FIELD_BYTES = 8;
export const RECORD_PHOTO_PROOF_MIN_LEN =
  RECORD_PHOTO_PROOF_DISCRIMINATOR_BYTES +
  RECORD_PHOTO_PROOF_HASH_BYTES +
  RECORD_PHOTO_PROOF_NUMERIC_FIELD_BYTES +
  RECORD_PHOTO_PROOF_NUMERIC_FIELD_BYTES +
  RECORD_PHOTO_PROOF_NUMERIC_FIELD_BYTES;
